// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: function.sql

package db

import (
	"context"
	"database/sql"
)

const generateMemberCode = `-- name: GenerateMemberCode :one
SELECT member_code FROM generate_member_code()
`

func (q *Queries) GenerateMemberCode(ctx context.Context) (sql.NullString, error) {
	row := q.queryRow(ctx, q.generateMemberCodeStmt, generateMemberCode)
	var member_code sql.NullString
	err := row.Scan(&member_code)
	return member_code, err
}
